<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Buscador de Conciertos</title>
</head>
<body>

  <!-- Navbar -->
  <nav>
    <div>
      <a href="">Buscador de Conciertos</a>
      
      <div>
        <a href="">Bandas</a>
        <a href="">Conciertos</a>
      </div>

      <div>
        <span>juan@unicen.edu.ar</span>
        <a href="">Cerrar sesión</a>
      </div>
    </div>
  </nav>

</body>
</html>