<?php require_once __DIR__ . '/layout/header.phtml'; ?>

<h2>Iniciar Sesión - Administrador</h2>
<form action="<?= BASE_URL ?>login" method="POST">
    <div>
        <label>Usuario (Email):</label>
        <input type="text" name="email" placeholder="Ingrese nombre de usuario" required>
    </div>
    <div>
        <label>Contraseña:</label>
        <input type="password" name="password" placeholder="Ingrese contraseña" required>
    </div>
    <button type="submit">Ingresar</button>
</form>

<?php require_once __DIR__ . '/layout/footer.phtml'; ?>
