<h1>Conciertos de la banda</h1>

<?php if (empty($concerts)) : ?>
    <p>No hay conciertos cargados para esta banda.</p>
<?php else : ?>
    <?php foreach ($concerts as $concert) : ?>
        <div>
            <h3><?= $concert->lugar ?></h3>
            <p>
                Fecha: <?= $concert->fecha ?>
            </p>
            <p>
                Ciudad: <?= $concert->ciudad ?>
            </p>
            <hr>
        </div>
    <?php endforeach; ?>
<?php endif; ?>